### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Oxotnuk** [the-mirror-gdp/the-mirror#104]
Weapon transfer error.

The error is that three weapons (shotgun, pistol, machine gun) that have a hand sign cannot be moved into the scene or, for example, placed above the table so that the player can come up and take their inventory.

Windows 10, Itch, Mirror version: Alpha version Gravity v6.0.259 - prod, docker open source.

1. Go to Mirror.
2. Press B to open the assembly user interface, Editor.
3. Transfer the 3D model to the scene (shotgun, pistol, machine gun) where there is a hand sign.

Screenshots:
![3](https://github.com/the-mirror-gdp/the-mirror/assets/86876393/3c73bde1-f7ef-4492-a9f5-c6f1c6ff9ecc)
![5](https://github.com/the-mirror-gdp/the-mirror/assets/86876393/10909ff0-2fdf-4424-93d5-d267e9872c61)

Device name: DESKTOP-LQO14G9
Processor: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 2.80 GHz
RAM: 8.00 GB (available: 7.69 GB)
Device code: A88A02A9-6C5D-4573-AD45-6CEA095BEEC6
Product code: 00331-10000-00001-AA015
System type: 64-bit operating system, x64 processor
Pen and touch input: Pen and touch input are not available for this monitor

**Comment by Oxotnuk** [comment]
> Weapon transfer error.
> 
> The error is that three weapons (shotgun, pistol, machine gun) that have a hand sign cannot be moved into the scene or, for example, placed above the table so that the player can come up and take their inventory.
> 
> Windows 10, Itch, Mirror version: Alpha version Gravity v6.0.259 - prod, docker open source.
> 
> 1. Go to Mirror.
> 2. Press B to open the assembly user interface, Editor.
> 3. Transfer the 3D model to the scene (shotgun, pistol, machine gun) where there is a hand sign.
> 
> Screenshots: ![3](https://private-user-images.githubusercontent.com/86876393/321611394-3c73bde1-f7ef-4492-a9f5-c6f1c6ff9ecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzU0NDQsIm5iZiI6MTcxMjgzNTE0NCwicGF0aCI6Ii84Njg3NjM5My8zMjE2MTEzOTQtM2M3M2JkZTEtZjdlZi00NDkyLWE5ZjUtYzZmMWM2ZmY5ZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDExMzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZTk1NDAwYTY5OGU0MGU4MTFiMjBhYmVlNWVjODAzMGRmMjI3YTMwYjViYTUyY2EzNWU3OWI2MzM5MmUyMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bK1ueEmJ8ZA1OiqDzuRPobaHDHmlYboEiVOctRTMILc) ![5](https://private-user-images.githubusercontent.com/86876393/321611415-10909ff0-2fdf-4424-93d5-d267e9872c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzU0NDQsIm5iZiI6MTcxMjgzNTE0NCwicGF0aCI6Ii84Njg3NjM5My8zMjE2MTE0MTUtMTA5MDlmZjAtMmZkZi00NDI0LTkzZDUtZDI2N2U5ODcyYzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDExMzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MjUzOTBhMzNhNWI0ZTg0ZjViZWExMGJlOGJhODMzODgxZjBkMGFlNjZlMjNiNGY3NTVhNDdlZmNmY2FhZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VoODBxRBnStVqITZZj9M3_EaxFojqDNOj6yBAZxgPRo)
> 
> Device name: DESKTOP-LQO14G9 Processor: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 2.80 GHz RAM: 8.00 GB (available: 7.69 GB) Device code: A88A02A9-6C5D-4573-AD45-6CEA095BEEC6 Product code: 00331-10000-00001-AA015 System type: 64-bit operating system, x64 processor Pen and touch input: Pen and touch input are not available for this monitor

**Comment by Kluskey** [comment]
Dup of https://github.com/the-mirror-gdp/the-mirror/issues/105
