### ISSUE TITLE
[Bug] Recent algorithm on the Home page does not work

### ISSUE THREAD

**Issue by lizathemirror** [the-mirror-gdp/the-mirror#118]
PC win10
v6.1.79-staging

Steps to reproduce:

1. Open the Home page
2. Pay attention to spaces in the Recent section 
3. Enter any space except the first one in the Recent section 
4. Return to the Home page
5. Pay attention to spaces in the Recent section 

Actual Result:
The space order in the Recent section is the same as it was before entering the space

Expected Result:
The last space entered must be in the first position in Recentession in the  Recent section 

Attachments:

https://github.com/the-mirror-gdp/the-mirror/assets/116018527/5e661823-c6b2-476e-bea2-20ec21f41520

**Comment by RevoluPowered** [comment]
We just tested and this is working for us, can you please re-test.

If the issue is still present please let us know the account used.

**Comment by lizathemirror** [comment]
It's fixed on v6.1.82-local
