### ISSUE TITLE
[Bug] Other users are not shown in the space

### ISSUE THREAD

**Issue by lizathemirror** [the-mirror-gdp/the-mirror#119]
PC win10
v6.1.79-staging

Steps to reproduce:

1. Open 2 sessions of the app on different machines 
2. Enter the same space on both PCs
3. Pay attention that there is no one else in the space (open the Users window in the top hub in the Build mode) on both machines 
4. Add any new objects to the space or change the position of any object on one of the machines
5. Pay attention that the changes are visible from another machine

Actual Result:
When logging into the same space from different computers, the users are not visible to each other, but the changes they make are displayed 

Expected Result:
Users should see each other in the space

Attachments:
The video shows the behavior on one of the machines while new objects were being added from the other machine

https://github.com/the-mirror-gdp/the-mirror/assets/116018527/b6d6f0c5-0ead-4b68-9626-37a048a84995

**Comment by Kluskey** [comment]
Fixed by @RevoluPowered
