### ISSUE TITLE
[Bug] Space publishing doesn't work 

### ISSUE THREAD

**Issue by lizathemirror** [the-mirror-gdp/the-mirror#123]
PC win10
v6.1.79-staging

Steps to reproduce:

1. Open any published space window 
2. Press Play button
3. Pay attention that the opened space is in the Build mode instead of the Play mode (press B to check it)
4. Return to the space window and try to create a new server via the Create new button
5. Pay attention to the error message 

Actual Result:
All the play buttons (the play buttons on the spaces' cards on all tabs and the play button on the space window) open the Build mode instead of the Play mode. The Create Server button causes an error message and doesn't create a new server

Attachments:

https://github.com/the-mirror-gdp/the-mirror/assets/116018527/70a91c0c-b1f8-460a-8c94-dd114110d972

**Comment by RevoluPowered** [comment]
I'm going to take this task now.

**Comment by RevoluPowered** [comment]
Space publishing is working but the UI is a little confusing with the play button

**Comment by RevoluPowered** [comment]
Tasks
- [x] Backend issue with some spaces causing the publish to outright fail
- [x] When publishing a space from the Menu it fails to update the status and text of the publish button and also fails to refresh with the server in the list, it also fails to make the + Create New button non grey
- [x] Clicking should be blocked on the create new button until the space has been published, perhaps add a tooltip.

**Comment by RevoluPowered** [comment]
We've fixed this in the latest version.
