### ISSUE TITLE
[Bug] Sort by Last Updated don't work on My Spaces and Discover tabs

### ISSUE THREAD

**Issue by lizathemirror** [the-mirror-gdp/the-mirror#124]
PC win10
v6.1.79-staging

Steps to reproduce:

1. Open the My Spaces or Discover tab
2. Set sorting to Last Updated
3. Pay attention to the Updated date of the spaces

Actual Result:
Spaces on the My Spaces and Discover tabs are dispayed in random order and not sorted by edit date.

Expected Result:
A fter sorting by Last Updated, spaces should appear in order from most recently edited to least recently edited.

Attachments:

https://github.com/the-mirror-gdp/the-mirror/assets/116018527/1593db26-3947-470a-8a43-38ca6a4f354f

**Comment by RevoluPowered** [comment]
We've fixed this, it was sorting by createdAt
