### ISSUE TITLE
[Bug] Following instructions in README (for Linux), many errors shown in dialogs

### ISSUE THREAD

**Issue by truedat101** [the-mirror-gdp/the-mirror#17]
## Bug

errors in import  of project on Linux Ubuntu 22.04

## To reproduce

- follow guide
- https://github.com/the-mirror-gdp/the-mirror?tab=readme-ov-file#get-started
- do the optional step to install submodules
- Using master branch, url for binary: https://storage.googleapis.com/mirror_native_client_builds/Engine/41ba769a/MirrorGodotEditorLinux.x86_64
- import the project 
Note warnings:
![Screenshot from 2024-03-17 12-30-09](https://github.com/the-mirror-gdp/the-mirror/assets/64202/1967eb82-da8c-40cd-a72b-3121f6954385)

As import proceeds in engine, errors appear

![Screenshot from 2024-03-17 12-30-50](https://github.com/the-mirror-gdp/the-mirror/assets/64202/40dacedd-dd93-4e20-b528-25a715f8391e)
![Screenshot from 2024-03-17 12-31-10](https://github.com/the-mirror-gdp/the-mirror/assets/64202/a6d68c74-86d3-4b10-9b5e-37d8fa8d3298)

Finally, Mirror launches.  There is an additional warning about client being out of date:

![Screenshot from 2024-03-17 12-31-10](https://github.com/the-mirror-gdp/the-mirror/assets/64202/666d8476-820a-41c6-a134-fae1cb4e0fe8)

The main menu loads, however, experienced hanging when trying to exit one of the games.

## Workarounds

TBD

**Comment by aaronfranke** [comment]
> import the project
> Note warnings:

That allows us to pin the Godot app to a specific engine hash with a warning. Ideally this would indicate that you have the wrong engine version. However in this particular case you can ignore it, the engine fork is a bit in flux right now.

> As import proceeds in engine, errors appear

That is an upstream Godot bug https://github.com/godotengine/godot/issues/36713, the first time you open the editor it will fail to import. Please read step 4 of the instructions in the README.

> There is an additional warning about client being out of date:

Thanks, this is a known problem: https://github.com/the-mirror-gdp/the-mirror/issues/16

> The main menu loads, however, experienced hanging

This is also a known problem, it's slower than it was before open sourcing. It's a high priority to fix this.

**Comment by truedat101** [comment]
great, sounds like these are previously identified.  Maybe a mention in the README of ignoring spurious warnings.  It wasn't obvious that step 4 fixes whatever might be wrong.

**Comment by Kluskey** [comment]
Thanks @truedat101! I've updated the readme here https://github.com/the-mirror-gdp/the-mirror/commit/118fae7f409385f3bc7d06ca4eec7ad3ce2c3633, so I'll close this.

**Comment by truedat101** [comment]
awesome turn around.  Much appreciated.
