### ISSUE TITLE
[Proposal]

### ISSUE THREAD

**Issue by Clydeyabut** [the-mirror-gdp/the-mirror#231]
**The proposal**
_Please include as much detail as possible. Screenshots, videos, diagrams, etc. are super helpful and will help your proposal be implemented. Loom makes videos super easy._

**Would you be able to implement it?**
_Being able to spearhead it will greatly increase the odds of it being merged in. We're happy to review PRs :)_

**Additional context**

**Comment by RevoluPowered** [comment]
Sorry this proposal should include detail asking for what you want implemented, please edit this and ask us to re-open if you feel like we closed it unfairly.
