### ISSUE TITLE
[Bug] Speed up Space list using /discover-v3 route without popular Spaces arg

### ISSUE THREAD

**Issue by Kluskey** [the-mirror-gdp/the-mirror#4]
The Space list loading currently takes a long time due to our popular list functionality. It'd be better to just use it without the popular functionality since this will also be refactored with the new routes for locally-hosted multiplayer hosts to discover each other.

Acceptance criteria:

- Discover is the new combined tab on the app
- Cache so that it doesn’t rerun the Space list query each time
- Add a refresh button between the sort and the search to rerun the query
- Sorts: Top-rated (default), last updated. (Don’t include alphabetical)
- Homepage: Show discover instead of popular for the top row

**Comment by RevoluPowered** [comment]
Fixed in the latest version, it is much better now and linked commit.
