### ISSUE TITLE
[Build Bug] Problems building Godot fork using GitHub Actions

### ISSUE THREAD

**Issue by VladimirLevadnij** [the-mirror-gdp/the-mirror#43]
I'm creating an issue in this repository because this repository is an issue hub, but this issue concerns a Godot fork in a child repository https://github.com/the-mirror-gdp/godot

Problems building a Godot fork using GitHub Actions. For Linux and other platforms it produces errors. As I understand it, there are errors with tinfo, imalloc, i_malloc, __libc_malloc, an error in the operation of the linker.

Respected @aaronfranke on Discord commented:

> The linker fails with Jolt, we don't know why.
> 
> Prior to open sourcing, we only tested Windows, Mac, and Linux builds all without sanitizers. Some work will be required to fix building with sanitizers and on Android, iOS, and web.

> The Linux build works fine. It is just sanitizers that don't work.

> The problem is with our build system or code in the-mirror-gdp/godot, not with GitHub Actions in the-mirror-gdp/godot. The actions are "supposed to" work but don't.

> If you want to try and solve it you are welcome to. I don't really know what to do to fix it.

We need someone who can figure out this problem. Perhaps this person is respected @AndreaCatania who implemented the JoltPhysics functionality in this Godot fork https://github.com/jrouwe/JoltPhysics

![image](https://github.com/the-mirror-gdp/the-mirror/assets/20191527/726c39c9-a199-4066-9092-471a8783a9e4)

![image](https://github.com/the-mirror-gdp/the-mirror/assets/20191527/b9ceee4e-0d61-4ad1-8043-941390506a13)

![image](https://github.com/the-mirror-gdp/the-mirror/assets/20191527/5a856a24-9411-4ae4-893a-a6a369c709b7)

**Comment by Kluskey** [comment]
@VladimirLevadnij Thank you for submitting this; would you open the issue in https://github.com/the-mirror-gdp/godot? That'd be easier to track with having fork-related issues in the fork repo. 

I'll close this in the meantime since the new one will be open. Thanks!
