### ISSUE TITLE
Create documentation for building a Godot fork

### ISSUE THREAD

**Issue by VladimirLevadnij** [the-mirror-gdp/the-mirror#44]
I'm creating an issue in this repository because this repository is an issue hub, but this issue concerns a Godot fork in a child repository https://github.com/the-mirror-gdp/godot

Since the Godot fork with expanded functionality is an important component of The Mirror project, it is necessary to place instructions in the official documentation in the "Open-Source Code" section for assembling working editor applications based on this Godot fork, at least for the main platforms Windows, macOS and Linux.

https://docs.themirror.space/docs/category/open-source-code

Currently there is a problem with using GitHub Actions for building, this is written in the issue https://github.com/the-mirror-gdp/godot/issues/2

While building using GitHub Actions does not work, you can write the build process using SCons in the documentation.

Respected @aaronfranke on Discord commented:

> I have only tested compiling locally on Windows and macOS, just with scons.

> Prior to open sourcing, we only tested Windows, Mac, and Linux builds all without sanitizers. Some work will be required to fix building with sanitizers and on Android, iOS, and web.

It turns out that the first step in the documentation is to describe how to build without sanitizers, additionally indicating in the documentation the reason why sanitizers are not currently used, so that users of the documentation do not have unnecessary questions.

**Comment by aaronfranke** [comment]
The way you compile without sanitizers is by just... not enabling sanitizers.

Docs: https://github.com/the-mirror-gdp/godot?tab=readme-ov-file#compiling-from-source

**Comment by VladimirLevadnij** [comment]
> The way you compile without sanitizers is by just... not enabling sanitizers.

Thank you for your comment, I think when the time comes, since this Issue is not a high priority, this information would be better described in The Mirror's documentation.

**Comment by VladimirLevadnij** [comment]
I found the information I was looking for, these repositories have everything you need to create release builds.

Build scripts used for official Godot Engine.
https://github.com/godotengine/godot-build-scripts

Godot engine build containers.
https://github.com/godotengine/build-containers

Godot's buildroot soft-fork for generating toolchains to make portable Linux releases of Godot games.
https://github.com/godotengine/buildroot

**Comment by Kluskey** [comment]
Thanks @aaronfranke and @VladimirLevadnij, I'll close this then.
