### ISSUE TITLE
[Cleanup] We need to clean up the file mirror-godot-app/README.md

### ISSUE THREAD

**Issue by VladimirLevadnij** [the-mirror-gdp/the-mirror#73]
**What needs to be cleaned up?**

We need to clean up the file mirror-godot-app/README.md

I think there are different parts of the text that need to be changed, but the main thing is that there are a lot of irrelevant / broken links that lead either to a remote or closed repository in the group https://github.com/the-mirror-megaverse/

**Can you do this yourself? Contributions are greatly appreciated!**

It is better to carry out this work to the main team members who know exactly all the relevant information and relevant links.

**Comment by Kluskey** [comment]
Thanks for the catch; I'll take this on. Yes it definitely needs to be cleaned up :)

**Comment by VladimirLevadnij** [comment]
@Kluskey Hello, you deleted the old file README.md So it turns out there was no useful information at all?

**Comment by Kluskey** [comment]
> @Kluskey Hello, you deleted the old file README.md So it turns out there was no useful information at all?

There's some useful info, but it should be moved to the https://docs.themirror.space site.

**Comment by VladimirLevadnij** [comment]
> There's some useful info, but it should be moved to the https://docs.themirror.space site.

I see, thanks!
